server.port=${PORT:10000}

spring.datasource.url=jdbc:postgresql://dpg-d7fbsi57vvec739k4h5g-a/nexaverse_db
spring.datasource.username=nexaverse_db_user
spring.datasource.password=hPsHjDHFp8AHoHMmRNFHBa1gL8hZkNLh
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.data.redis.host=red-d7fs30471suc73bicapg
spring.data.redis.port=6379

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

spring.ai.openai.api-key=${GROQ_API_KEY}
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile

jwt.secret=${JWT_SECRET:nexaverse_super_secret_key_2024}
jwt.expiration=86400000

logging.level.root=INFO
logging.level.com.nexaverse=DEBUG

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true