spring.application.name=nexaverse
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/nexaverse_db
spring.datasource.username=postgres
spring.datasource.password=Vaishnavi@1510

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Virtual Threads
spring.threads.virtual.enabled=true

# JWT
jwt.secret=nexaverse-super-secret-key-2026-make-it-long-enough-for-security
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.enabled=true

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=nexaverse-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer